
namespace EventIAConstructor.CommandScript
{
    public enum CommandScriptType
    {
        TALK                    = 0,
        EMOTE                   = 1,
        FIELD_SET               = 2,
        MOVE_TO                 = 3,
        FLAG_SET                = 4,
        FLAG_REMOVE             = 5,
        TELEPORT_TO             = 6,
        QUEST_EXPLORED          = 7,
        KILL_CREDIT             = 8,
        RESPAWN_GAMEOBJECT      = 9,
        TEMP_SUMMON_CREATURE    = 10,
        OPEN_DOOR               = 11,
        CLOSE_DOOR              = 12,
        ACTIVATE_OBJECT         = 13,
        REMOVE_AURA             = 14,
        CAST_SPELL              = 15,
        PLAY_SOUND              = 16,
        CREATE_ITEM             = 17,
        DESPAWN_SELF            = 18,
        PLAY_MOVIE              = 19,
        MOVEMENT                = 20,
        SET_ACTIVEOBJECT        = 21,
        SET_FACTION             = 22,
        MORPH_TO_ENTRY_OR_MODEL = 23,
        MOUNT_TO_ENTRY_OR_MODEL = 24,
        SET_RUN                 = 25,
        ATTACK_START            = 26,
        GO_LOCK_STATE           = 27,
        STAND_STATE             = 28,
        MODIFY_NPC_FLAGS        = 29,
        SEND_TAXI_PATH          = 30,
        TERMINATE_SCRIPT        = 31,
        PAUSE_WAYPOINTS         = 32,
        XP_USER                 = 33,
        TERMINATE_COND          = 34,
        SEND_AI_EVENT           = 35,
        SET_FACING              = 36,
        MOVE_DYNAMIC            = 37,
        SEND_MAIL               = 38,
        SET_FLY                 = 39,
        DESPAWN_GO              = 40,
        RESPAWN                 = 41,
    }
}