
namespace EventIAConstructor.EventAIMetadata
{
    /// <summary>
    /// 
    /// </summary>
    public enum ActionType : int
    {
        NONE                        = 0,
        TEXT                        = 1,
        SET_FACTION                 = 2,
        MORPH_TO_ENTRY_OR_MODEL     = 3,
        SOUND                       = 4,
        EMOTE                       = 5,
        RANDOM_SOUND                = 9,
        RANDOM_EMOTE                = 10,
        CAST                        = 11,
        SUMMON_DURATION             = 12,
        THREAT_SINGLE_PCT           = 13,
        THREAT_ALL_PCT              = 14,
        QUEST_EVENT                 = 15,
        QUEST_CASTCREATUREGO        = 16,
        SET_UNIT_FIELD              = 17,
        SET_UNIT_FLAG               = 18,
        REMOVE_UNIT_FLAG            = 19,
        AUTO_ATTACK                 = 20,
        COMBAT_MOVEMENT             = 21,
        SET_PHASE                   = 22,
        INC_PHASE                   = 23,
        EVADE                       = 24,
        FLEE_FOR_ASSIST             = 25,
        QUEST_EVENT_ALL             = 26,
        CASTCREATUREGO_ALL          = 27,
        REMOVEAURASFROMSPELL        = 28,
        RANGED_MOVEMENT             = 29,
        RANDOM_PHASE                = 30,
        RANDOM_PHASE_RANGE          = 31,
        SUMMON                      = 32,
        KILLED_MONSTER              = 33,
        SET_INST_DATA               = 34,
        SET_INST_DATA64             = 35,
        UPDATE_TEMPLATE             = 36,
        DIE                         = 37,
        ZONE_COMBAT_PULSE           = 38,
        CALL_FOR_HELP               = 39,
        SET_SHEATH                  = 40,
        FORCE_DESPAWN               = 41,
        SET_INVINCIBILITY_HP_LEVEL  = 42,
        MOUNT_TO_ENTRY_OR_MODEL     = 43,
        CHANCED_TEXT                = 44,
        THROW_AI_EVENT              = 45,
        SET_THROW_MASK              = 46,
        SET_STAND_STATE             = 47,
    }
}
